# Generated by Django 5.2.1 on 2025-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubnetCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr_input', models.CharField(max_length=18)),
                ('subnet_mask', models.CharField(max_length=18)),
                ('total_ip', models.IntegerField()),
                ('usable_host', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
