# Generated by Django 5.2.1 on 2025-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmath', '0002_subnetcalculation_broadcast_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnetcalculation',
            name='binary_num',
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
    ]
